
FROM mcr.microsoft.com/dotnet/aspnet:7.0 as base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
COPY . /src
WORKDIR /src
RUN ls
RUN dotnet build "spinnaker.sln" -c Release -o /app/build
#RUN dotnet build "spinnaker.web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "spinnaker.sln" -c Release -o /app/publish
#RUN dotnet publish "spinnaker.web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "spinnaker.web.dll"]
